services:
  api:
    image: sourdough-api
    build:
      context: backend
      dockerfile: Dockerfile
    depends_on:
      - mongodb
    # docker build -t sourdough-api
    # docker run -p 3000:3000 --name api sourdough-api
    ports:
      - '3000:3000'
    volumes: #remove when in production
      - ./backend/src:/app/src
    env_file:
      - backend/.env
    environment: # where is this defined?
      # - MONGODB_CONNECTION_STRING=$(MONGODB_CONNECTION_STRING)
      - MONGODB_CONNECTION_STRING=mongodb://mongodb:27017/sourdough

  frontend:
    image: sourdough-frontend
    build:
      context: frontend
      dockerfile: Dockerfile
    ports:
      - '5173:5173'
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public
    env_file:
      - frontend/.env

  mongodb:
    image: mongo
    ports:
      - '27017:27017'
    volumes: #stores the data on the hard disk
      - ./data:/data/db

  tests:
    image: sourdough-api
    depends_on:
      - api
    volumes:
      - ./backend/src/example-api-tests.js/:/app/backend/src/example-api-tests.js
      - ./backend/src:/app/backend/src
    working_dir: /app
    command: node ./backend/src/example-api-tests.js
    env_file:
      - backend/.env
    environment: # where is this defined?
      - MONGODB_CONNECTION_STRING=mongodb://mongodb:27017/sourdough
