version: '3' # specific to swarm

services:
  api:
    image: sourdough-api
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mongodb
    # docker build -t sourdough-api
    # docker run -p 3000:3000 --name api sourdough-api
    ports:
      - '3000:3000'
    volumes: #remove when in production
      - ./src:/app/src
    #env_file:
    #  - .env
    environment: # where is this defined?
      - MONGODB_CONNECTION_STRING=mongodb://mongodb:27017/sourdough

  mongodb:
    image: mongo
    ports:
      - '27017:27017'
    volumes: #stores the data on the hard disk
      - ./data:/data/db

  tests:
    image: sourdough-api
    depends_on:
      - api
    volumes:
      - ./src/tests.js:/app/src/tests.js
    working_dir: /app
    command: node src/tests.js
