@startuml SourdoughAPP
class User {
  name: string
  email: string
  recipes: [Recipe]
  events: [Event]
  notes: [Note]

  constructor(name: string, email: string)

  createRecipe(title: string, date: date, ...ingredients: [string])
  addNote(recipe: Recipe)


}
@enduml
